// Entry point for the shell - boots Playground cross-origin

import { createBlock, serialize, parse, getBlockType } from '@wordpress/blocks';
import { registerCoreBlocks } from '@wordpress/block-library';
import { importPosts } from './lib/import.mjs';
import { readPosts } from './lib/read-posts.mjs';
import { getChangedFiles } from './lib/changed-files.mjs';
import { startChange, save as commitChanges } from './lib/change.mjs';
import { createPublish } from './lib/publish.mjs';
import { createGitWriter } from './lib/git-writer.mjs';
import {
  getToken, clearToken, exchangeCodeForToken, beginAuthorization, stateMatches,
} from './lib/auth.mjs';
import { VOCAB } from './lib/vocabulary.mjs';
import { CONTENT_REPO, CONTENT_BRANCH, PREVIEW_URL_FOR } from './config.mjs';

// The broker's own vhost proxies this path to it (infra/ansible/roles/editor_shell's
// edit.conf.j2, `location = /token`) so this is same-origin wherever the shell is
// served, including the Playwright harness's local server.
const BROKER_PATH = '/token';

// The content repository every GitHub call below targets — the same repository
// content-source.mjs reads from (unauthenticated) to import. No longer duplicated: both
// now derive from the fork's single declaration in jamground.config.mjs, so the two cannot
// drift apart the way the old pair of literals could.
const REPO = CONTENT_REPO;
const BASE_BRANCH = CONTENT_BRANCH;

// `preview` has no control: previews were dropped for this release, and a preview URL is
// surfaced on the change instead of as a shell action, so there is nothing this identifier
// could ever do — a control that can never act would be the same defect as one with no
// handler. `VOCAB.preview` stays anyway: test/gates/editorial-vocabulary.test.mjs scans this
// module's string literals, not the live page, so the term still has to live here.
const ACTION_CONTROL_IDS = ['startAChange', 'save', 'sendForReview', 'publish'];

// The block API every export-direction call below needs — `parse` and `getBlockType` for
// attribute-guard.mjs / export.mjs, on top of the `createBlock`/`serialize` the import
// direction already uses. Built once, at module scope, from the same registration that
// already ran above for window.wpBlocksAPI.
const blockApi = { createBlock, serialize, parse, getBlockType };

// Generated by the shell, never typed by an editor. A fuller scheme —
// `content/<editor-handle>/<slug>-<ulid>` — would need the editor's GitHub handle and the
// entity's own slug, neither of which this function has reason to reach for; a
// session-unique suffix is enough to open a branch nothing else collides with.
function generateBranchName() {
  const suffix = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
  return `content/change-${suffix}`;
}

// Expose the blocks API and register core blocks immediately
// This ensures the API is available for pages that don't boot Playground
try {
  registerCoreBlocks();

  // registerCore wrapper function
  function registerCore(api) {
    // registerCoreBlocks() has already been called above
    // This function is for compatibility with the contract
  }

  window.wpBlocksAPI = {
    createBlock,
    serialize,
    parse,
    registerCore,
  };
} catch (error) {
  console.error('[entry.mjs] Error setting up blocks API:', error);
  window.wpBlocksError = error;
}

// Blueprint configuration for Playground - inlined from blueprint.json by build.mjs
// Falls back to inline config if not inlined
const blueprint = typeof window !== 'undefined' && window.__blueprint
  ? window.__blueprint
  : {
      login: true,
      landingPage: '/wp-admin/',
      preferredVersions: {
        php: '8.3',
        wp: '7.1'
      },
      steps: []
    };

// mu-plugin PHP source - inlined from mu-plugin/jamground.php by build.mjs. The
// blueprint carries no content; the shell writes this into the WASM
// filesystem itself, after boot.
const muPluginSource = typeof window !== 'undefined' && window.__muPluginSource
  ? window.__muPluginSource
  : '';

async function installMuPlugin(client) {
  if (!muPluginSource) {
    console.warn('[entry.mjs] No mu-plugin source to install');
    return;
  }
  const root = await client.documentRoot;
  await client.mkdir(root + '/wp-content/mu-plugins');
  await client.writeFile(root + '/wp-content/mu-plugins/jamground.php', muPluginSource);
}

// Every fresh WordPress install ships its own seed content: a "Hello world!" post, a "Sample
// Page", and a canned comment on the post. None of them is a Jamground entity — they carry no
// `_jamground_id` and no `_jamground_source` — so the save path correctly declines to write
// them anywhere, and an editor who opens one and edits it is told "there is nothing new to
// save" about a post sitting in front of them in the list. That is a true statement about an
// entity the editor had no reason to believe was different from the others, which makes it
// indistinguishable from a bug.
//
// ORDERING IS LOAD-BEARING: this runs AFTER boot and BEFORE importPosts, which is the one
// moment when "everything in this database is WordPress's own seed data" is certainly true.
// Moved after the import, it would delete the imported content instead.
async function removeDefaultContent(client) {
  const root = await client.documentRoot;
  const code = `<?php require '${root}/wp-load.php';
    $ids = get_posts(['post_type' => 'any', 'post_status' => 'any', 'numberposts' => -1, 'fields' => 'ids']);
    foreach ($ids as $id) { wp_delete_post($id, true); }
    $cids = get_comments(['fields' => 'ids']);
    foreach ($cids as $cid) { wp_delete_comment($cid, true); }
    echo json_encode(['posts' => count($ids), 'comments' => count($cids)]);`;
  const result = await client.run({ code });
  return JSON.parse(result.text);
}

// --- Begin the OAuth flow ---
//
// The shell's own page never navigates. The sign-in control opens GitHub's authorize
// screen in a popup; the popup lands back on the registered callback, which is this
// same page — so this page must recognise when IT IS the popup landing on that
// callback and hand off instead of booting Playground a second time (14-18s a boot).
// That is the one thing distinguishing a callback load from an ordinary one: it has
// an `opener` and carries `code` or `error` in its own query string.
function isOAuthCallback() {
  if (!window.opener) return false;
  const params = new URLSearchParams(window.location.search);
  return params.has('code') || params.has('error');
}

// Hands the result to the opener over `postMessage`, pinned to the exact origin on
// both sides — this page's own origin, never `*` — the same discipline the broker's own
// CORS already requires. Then closes; there is nothing else for this
// window to do.
function handleOAuthCallback() {
  const params = new URLSearchParams(window.location.search);
  const message = {
    source: 'jamground-oauth',
    code: params.get('code'),
    state: params.get('state'),
    error: params.get('error'),
  };
  window.opener.postMessage(message, window.location.origin);
  window.close();
}

async function boot() {
  try {
    const iframe = document.getElementById('wp');

    if (!iframe) {
      console.error('[entry.mjs] iframe with id="wp" not found');
      window.jamgroundBootError = 'iframe not found';
      return;
    }

    console.log('[entry.mjs] Starting Playground boot');

    // Dynamically import the client from unpkg
    const { startPlaygroundWeb } = await import('https://unpkg.com/@wp-playground/client@3.1.50/index.js');

    const client = await startPlaygroundWeb({
      iframe,
      remoteUrl: 'https://playground.wordpress.net/remote.html',
      blueprint
    });

    console.log('[entry.mjs] Waiting for Playground to be ready');
    await client.isReady();

    console.log('[entry.mjs] Installing mu-plugin');
    await installMuPlugin(client);

    console.log('[entry.mjs] Removing WordPress default content');
    try {
      window.jamgroundDefaultContentRemoved = await removeDefaultContent(client);
    } catch (removeError) {
      // Not fatal: leaving WordPress's seed posts in place is confusing, but refusing to boot
      // over it would be worse. Recorded so the Playwright suite can assert on it.
      console.error('[entry.mjs] Removing default content failed:', removeError);
      window.jamgroundDefaultContentError = removeError.message;
    }

    console.log('[entry.mjs] Importing content');
    // registerCoreBlocks() has already been called at module load time to expose
    // window.wpBlocksAPI. The API is ready for use here.
    const api = { createBlock, serialize };
    try {
      window.jamgroundImportResult = await importPosts({
        client, api, fetchImpl: window.fetch.bind(window), locale: 'en-US',
      });
    } catch (importError) {
      console.error('[entry.mjs] Import failed:', importError);
      window.jamgroundImportError = importError.message;
    }

    console.log('[entry.mjs] Playground is ready');
    window.jamgroundReady = true;
    window.jamgroundClient = client;

  } catch (error) {
    console.error('[entry.mjs] Error booting Playground:', error);
    window.jamgroundBootError = error.message;
  }
}

// Shell UI controls: compose them in host-page scope, token stays in closure.
// The shell exposes these functions; callers invoke them without touching storage.
window.jamgroundShell = (() => {
  // Token is held only in this closure, never in localStorage/sessionStorage
  let token = null;

  // The PKCE verifier and anti-forgery `state` for a popup round trip in flight, plus
  // a reference to the popup itself so the message listener can check `event.source`.
  // Closure-only, same as the token, and cleared the moment the round trip ends
  // either way — never written anywhere durable.
  let pending = null;

  // The open change's branch and pull request, set by startAChange and read by save,
  // sendForReview and publish — this is session state the shell is
  // responsible for, so an editor is never asked to name a branch or a pull request.
  // Closure-only, same discipline as the token: nothing here reaches storage.
  let change = null;

  function setActionControlsEnabled(enabled) {
    for (const id of ACTION_CONTROL_IDS) {
      const el = document.getElementById(`jamground-control-${id}`);
      if (el) el.disabled = !enabled;
    }
    const signInButton = document.getElementById('jamground-control-signIn');
    if (signInButton) signInButton.disabled = enabled;
  }

  // Enable/disable the startAChange control based on token && !change. Called after
  // startAChange succeeds (to disable), after publish clears the change (to enable),
  // and during sign-out (to disable). The other three action controls are managed by
  // setActionControlsEnabled; this one needs independent tracking.
  function setStartAChangeEnabled(enabled) {
    const el = document.getElementById('jamground-control-startAChange');
    if (el) el.disabled = !enabled;
  }

  // `link` is optional and is rendered as a real anchor. Built with createElement and textContent
  // rather than by assigning innerHTML: the only thing that ever reaches this line is our own
  // vocabulary plus a URL derived from the fork's own configuration, and it should stay that way
  // by construction rather than by everyone remembering.
  function showStatus(message, link) {
    const el = document.getElementById('jamground-status');
    if (!el) return;
    el.textContent = message || '';
    if (!link) return;
    el.appendChild(document.createElement('br'));
    const a = document.createElement('a');
    a.href = link;
    a.textContent = link;
    a.target = '_blank';
    a.rel = 'noopener';
    el.appendChild(a);
  }

  function onPopupMessage(event) {
    if (!pending) return;
    // Exact origin on both sides, never '*'.
    if (event.origin !== window.location.origin) return;
    if (event.source !== pending.popup) return;
    const data = event.data;
    if (!data || data.source !== 'jamground-oauth') return;

    window.removeEventListener('message', onPopupMessage);
    const { verifier, state, brokerUrl } = pending;
    pending = null;

    if (data.error) {
      showStatus(VOCAB.signInFailed);
      return;
    }
    if (!stateMatches(data.state, state)) {
      // Refused WITHOUT ever calling the broker.
      showStatus(VOCAB.signInNotVerified);
      return;
    }
    exchangeCodeForToken({ brokerUrl, code: data.code, codeVerifier: verifier })
      .then((exchanged) => {
        token = exchanged;
        setActionControlsEnabled(true);
        setStartAChangeEnabled(true);
        // A message, not an empty string — otherwise signing in and nothing happening
        // would look identical.
        showStatus(VOCAB.signedIn);
      })
      .catch((error) => {
        console.error('[jamgroundShell] token exchange failed:', error);
        showStatus(VOCAB.signInFailed);
      });
  }

  return {
    // Return current in-memory token (memory-only, no storage)
    getToken() {
      return token;
    },

    // Begins the flow from the sign-in control: opens GitHub's authorize screen in a
    // popup so the shell's own page never navigates and the verifier/state survive
    // in this closure. A blocked popup is a real failure for a
    // non-technical editor, so it gets a plain-language message rather than silence.
    async beginSignIn({ brokerUrl = BROKER_PATH } = {}) {
      const { url, verifier, state } = await beginAuthorization();
      const popup = window.open(url, 'jamground-sign-in', 'width=600,height=700');
      if (!popup) {
        showStatus(VOCAB.signInPopupBlocked);
        return false;
      }
      showStatus('');
      pending = { verifier, state, popup, brokerUrl };
      window.addEventListener('message', onPopupMessage);
      return true;
    },

    // Inspection seam for what is pending, not a way to write it anywhere durable —
    // this is the same closure `beginSignIn` set, read back rather than duplicated.
    getPendingAuthorization() {
      return pending ? { verifier: pending.verifier, state: pending.state } : null;
    },

    // Sign in directly with an already-obtained code and verifier — kept for the
    // broker-facing half of the flow exercised by this module's own tests; the popup control
    // above is what an editor actually drives.
    async signIn({ brokerUrl, code, codeVerifier, fetchImpl = fetch }) {
      try {
        token = await exchangeCodeForToken({ brokerUrl, code, codeVerifier, fetchImpl });
        setActionControlsEnabled(true);
        setStartAChangeEnabled(true);
        showStatus(VOCAB.signedIn);
        return token;
      } catch (error) {
        console.error('[jamgroundShell] signIn failed:', error);
        throw error;
      }
    },

    // Sign out: drop the token and return the shell to its pre-sign-in state
    signOut() {
      token = null;
      change = null;
      clearToken();
      setActionControlsEnabled(false);
      setStartAChangeEnabled(false);
    },

    // Start a change: create the branch and open the draft pull request BEFORE any
    // editing happens — Playground's native export can only do this at export time, so the
    // shell calls the GitHub API directly instead.
    // The shell is responsible for the actions its controls name, so starting
    // a second change while one is already open is a shell defect, not an editor error.
    async startAChange() {
      if (!token) throw new Error('startAChange: must sign in first');
      if (change) {
        showStatus(VOCAB.changeAlreadyOpen);
        throw new Error('startAChange: change already open');
      }
      try {
        const branch = generateBranchName();
        const pr = await startChange({
          title: 'Editorial change',
          baseBranch: BASE_BRANCH,
          branch,
          repo: REPO,
          token: token.access_token,
        });
        change = { branch, baseBranch: BASE_BRANCH, prNumber: pr.number, prNodeId: pr.node_id };
        window.jamgroundLastAction = { type: 'startAChange', branch, prNumber: pr.number };
        // The earliest moment the staging address is known. The site behind it does not exist
        // yet — the box builds it from the webhook this action just caused, which takes about a
        // minute — so the message says so rather than handing over a link that 404s and letting
        // the editor conclude the feature is broken.
        showStatus(`${VOCAB.changeStarted} — ${VOCAB.stagingPreparing}`, PREVIEW_URL_FOR(pr.number));
        setStartAChangeEnabled(false);
        return { success: true, branch, prNumber: pr.number };
      } catch (error) {
        console.error('[jamgroundShell] startAChange failed:', error);
        showStatus(VOCAB.startAChangeFailed);
        throw error;
      }
    },

    // Save: read whatever wp-admin has already persisted — dispatching Gutenberg's own save
    // across the Playground boundary has no channel here, since the shell cannot reach the
    // editor DOM without self-hosting Playground, which this project does not do — compare
    // it against the imported baseline, and commit only what differs — in one commit, onto the open
    // change's branch. An empty comparison commits nothing and says so, truthfully,
    // rather than reporting success for an action that did not happen.
    async save() {
      if (!token) throw new Error('save: must sign in first');
      if (!change) {
        showStatus(VOCAB.notInChange);
        throw new Error('save: start a change first');
      }
      try {
        const posts = await readPosts({ client: window.jamgroundClient });
        // The contract's timestamp fields are second-precision (see defs.ts's
        // `must be a real instant` refinement) — `Date#toISOString` always carries
        // milliseconds, so every real save would fail the schema without truncating them.
        const getUpdatedAt = () => new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');

        // `getChangedFiles` re-stamps `updatedAt` with whatever `getUpdatedAt` returns
        // before comparing — pass it a clock that never stops and every post looks
        // changed on every save, timestamp alone, which is exactly the false-positive
        // "nothing edited" idempotence promises. So content is checked first, holding
        // each post's own stored `updatedAt` steady (`getChangedFiles` takes no post
        // argument, so this runs one post at a time); a fresh timestamp is only used
        // below, for the posts that already differ on content.
        const changedPosts = posts.filter((post) =>
          getChangedFiles([post], { api: blockApi, getUpdatedAt: () => post.frontmatter.updatedAt }).length > 0,
        );
        window.jamgroundLastAction = { type: 'save', changed: changedPosts.length };

        if (changedPosts.length === 0) {
          showStatus(VOCAB.nothingToSave);
          return { success: true, changed: 0 };
        }

        const gitWriter = createGitWriter({ repo: REPO, token: token.access_token });
        await commitChanges({
          posts: changedPosts,
          message: 'Editorial update',
          gitWriter,
          baseBranch: change.baseBranch,
          branch: change.branch,
          api: blockApi,
          getUpdatedAt,
        });
        showStatus(VOCAB.saved);
        return { success: true, changed: changedPosts.length };
      } catch (error) {
        console.error('[jamgroundShell] save failed:', error);
        showStatus(VOCAB.saveFailed);
        throw error;
      }
    },

    // Send for review: mark the draft pull request ready. No REST route clears `draft`,
    // so this is the GraphQL mutation.
    async sendForReview() {
      if (!token) throw new Error('sendForReview: must sign in first');
      if (!change) {
        showStatus(VOCAB.notInChange);
        throw new Error('sendForReview: start a change first');
      }
      try {
        const pub = createPublish({ repo: REPO, token: token.access_token });
        const result = await pub.readyForReview({ prNodeId: change.prNodeId });
        window.jamgroundLastAction = { type: 'sendForReview', prNodeId: change.prNodeId, ...result };
        if (result && result.empty) {
          // No content difference: the change stays open, and the shell — never
          // publish.mjs — supplies the editor-facing words.
          showStatus(VOCAB.noContentChange);
        } else {
          showStatus(VOCAB.sentForReview);
        }
        return result || { success: true };
      } catch (error) {
        console.error('[jamgroundShell] sendForReview failed:', error);
        showStatus(VOCAB.sendForReviewFailed);
        throw error;
      }
    },

    // Publish: merge to the default branch. A 405 or 409 is the expected shape of "review
    // isn't done yet" — publish.mjs already turns that into the editorial
    // waiting-for-approval message rather than a throw, and that message, not API wording,
    // is what reaches the status line.
    async publish() {
      if (!token) throw new Error('publish: must sign in first');
      if (!change) {
        showStatus(VOCAB.notInChange);
        throw new Error('publish: start a change first');
      }
      try {
        const pub = createPublish({ repo: REPO, token: token.access_token });
        const result = await pub.publish({ prNumber: change.prNumber });
        window.jamgroundLastAction = { type: 'publish', prNumber: change.prNumber, ...result };
        if (result && result.empty) {
          // No content difference: no merge was issued, the change stays open, and
          // start-a-change stays disabled.
          showStatus(VOCAB.noContentChange);
        } else if (result && result.waiting) {
          showStatus(result.message);
        } else {
          showStatus(VOCAB.published);
          change = null;
          setStartAChangeEnabled(true);
        }
        return result;
      } catch (error) {
        console.error('[jamgroundShell] publish failed:', error);
        showStatus(VOCAB.publishFailed);
        throw error;
      }
    },
  };
})();

// Wire the sign-in control: labelled from vocabulary.mjs, and the only control
// operable before sign-in (the other four stay `disabled` until a token exists).
const signInButton = document.getElementById('jamground-control-signIn');
if (signInButton) {
  signInButton.textContent = VOCAB.signIn;
  signInButton.addEventListener('click', () => {
    window.jamgroundShell.beginSignIn().catch((error) => {
      console.error('[entry.mjs] beginSignIn failed:', error);
    });
  });
}

// Wire the four action controls: labelled from vocabulary.mjs (already set in
// index.html's own markup) and each backed by the shell method of the same name above.
// Every method already reports through showStatus on both its success and its failure
// path, so the handler here only needs to keep a rejection from reaching the console as
// an uncaught promise — the same discipline the sign-in control above already uses.
for (const id of ACTION_CONTROL_IDS) {
  const button = document.getElementById(`jamground-control-${id}`);
  if (button) {
    button.addEventListener('click', () => {
      window.jamgroundShell[id]().catch((error) => {
        console.error(`[entry.mjs] ${id} failed:`, error);
      });
    });
  }
}

// Boot when DOM is ready — unless this load IS the OAuth callback landing in the
// popup, in which case it hands off to the opener instead of booting Playground a
// second time.
if (isOAuthCallback()) {
  handleOAuthCallback();
} else if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot);
} else {
  boot();
}
